### ISSUE TITLE
cluster module support

### ISSUE THREAD

**Issue by cryptofuture** [paragi/timexe#12]
Does it support cluster or it would be running multiple tasks based on number of cores?

**Comment by paragi** [comment]
To the best of my knowledge node can only run single threaded.
Therefore any adaptation to parallel execution is outside of the scope
of the code.

**Comment by cryptofuture** [comment]
Code is similar to that
```
const cluster = require('cluster')
const numCPUs = require('os').cpus().length
if (cluster.isMaster) {
  for (let i = 0; i < numCPUs; i++) {
    cluster.fork()
  }
}
```

**Comment by paragi** [comment]
If you look in the documentation to cluster.fork:
https://millermedeiros.github.io/mdoc/examples/node_api/doc/cluster.html

You will see that the only thing shared is the TCP port.
Fork makes a copy of the timex instance, resulting in two instances
running independently.
eg. if you add a timer to the one, the other is not affected.

It’s hard for me to understand the use case of this? Why would you run
more than one instance of timex, with shared entries?

BR Simon Rigét

tor, 03 11 2022 kl. 10:06 -0700, skrev Eugene Gusev:

**Comment by paragi** [comment]
Timex will have the same behavior, during a fork, as the function
setTimeout()



tor, 03 11 2022 kl. 10:06 -0700, skrev Eugene Gusev:

**Comment by cryptofuture** [comment]
Thanks, clear now
