### ISSUE TITLE
Missing / Jumping Seconds

### ISSUE THREAD

**Issue by criticalboot** [paragi/timexe#3]
Line numbers 4 & 5 of the Output sample have same timestamp, in line number 5 the seconds expected is 54.
What do you think is happening.
  
```
timexe('* * * * * /1', function(){
  console.log("hello The time is now "+(new Date()).toLocaleString());
});
```

```
hello The time is now 4/19/2017, 2:36:50 PM
hello The time is now 4/19/2017, 2:36:51 PM
hello The time is now 4/19/2017, 2:36:52 PM
hello The time is now 4/19/2017, 2:36:53 PM
hello The time is now 4/19/2017, 2:36:53 PM
hello The time is now 4/19/2017, 2:36:55 PM
```

**Comment by paragi** [comment]
Thank you for reporting a possible issue.

Would you be so kind as to remove the toLocalString?
It would be nice to se the time with a higher resolution, to determine 
if its an error or a rounding problem.

Best regards
Simon Rigét

**Comment by criticalboot** [comment]
getting similar output.

```
let timexe = require('timexe');
timexe('* * * * * /1', function(){
  console.log("hello The time is now "+new Date());
});
```
```
hello The time is now Wed Apr 19 2017 18:27:13 GMT+0530 (IST)
hello The time is now Wed Apr 19 2017 18:27:14 GMT+0530 (IST)
hello The time is now Wed Apr 19 2017 18:27:15 GMT+0530 (IST)
hello The time is now Wed Apr 19 2017 18:27:16 GMT+0530 (IST)
hello The time is now Wed Apr 19 2017 18:27:16 GMT+0530 (IST)
hello The time is now Wed Apr 19 2017 18:27:18 GMT+0530 (IST)
hello The time is now Wed Apr 19 2017 18:27:19 GMT+0530 (IST)
hello The time is now Wed Apr 19 2017 18:27:20 GMT+0530 (IST)
```

**Comment by paragi** [comment]
Sorry, please try this:

   new Date().getTime();

to get milliseconds resolution

Den 19-04-2017 kl. 15:00 skrev criticalboot:

**Comment by criticalboot** [comment]
got similar output missed a second @ this time 
 1492667370002, 1492667370999
```
let timexe = require('timexe');
timexe('* * * * * /1', function(){
  console.log("hello The time is now "+(new Date().getTime()));
});
```
```
hello The time is now 1492667369001
hello The time is now 1492667370002
hello The time is now 1492667370999
hello The time is now 1492667372001
hello The time is now 1492667373000
```

**Comment by paragi** [comment]
Thank you

That's informative:
hello The time is now 1492667369001 
hello The time is now 1492667370002 
diff: 1001 ms 
hello The time is now 1492667370999 
diff: 997 ms 
hello The time is now 1492667372001 
diff: 1002 ms 
hello The time is now 1492667373000 
diff: 999 ms 

That is an inaccuracy of up to 3 milliseconds. Its 1 ms 
more than I have ever measured. Can you tell me something about the 
machine its running on? Is there a heavy load on it? Is the load 
constant? 

Best regards 
Simon Rigét

**Comment by paragi** [comment]
On closer inspection I see that the code aims to trigger at exactly 1.000 seconds. 
That means that the accuracy of +/- 2 ms still holds. 

Your misleading output is do to the way, the date function cuts off the milliseconds part, of the time.

To round it off and get at relatively more precise readout, you could try something like this:
` new Date(Math.round(new Date().getTime()/1000)*1000).toLocaleString();`

I'm sure you can make it prettier :)

I hope that helps?
   
Best regards
Simon Rigét
