### ISSUE TITLE
Can I Set The TimeZone?

### ISSUE THREAD

**Issue by RecordingTheSmile** [paragi/timexe#8]
Can I customize a time zone to schedule the job?

**Comment by paragi** [comment]
hmm - no. I think that localization is outside the scope of this package...?
In a browser, it uses the timezone of the client. In nodejs it uses UTC  (or what the host is set up to)
I would recommend that you make the conversion to host time, when you add the timer.  
It all depend on your use case? What is your suggestions?

**Comment by RecordingTheSmile** [comment]
> hmm - no. I think that localization is outside the scope of this package...?
> In a browser, it uses the timezone of the client. In nodejs it uses UTC (or what the host is set up to)
> I would recommend that you make the conversion to host time, when you add the timer.
> It all depend on your use case? What is your suggestions?

emm, sometimes I need to execute schedules in different timezones, I think it will be better if I can customize it.
And I actually want to know when will this package get UTC time, is it depends on what timezone the system set?

**Comment by paragi** [comment]
That is understandable. 
Usually the host uses UTC (with the exception of running timexe in browser?)
I would think, that conversion from local time to UTC, would happen in the client part of your app, or at least an understanding of the client timezone, and thereby, local timezone to convert from?

ex: 

    new Date('10/8/2021 14:00:00').toUTCString();
    
    or
    
    localDate.getUTCFullYear()+" "+localDate.getUTCMonth()+" "+localDate.getUTCDate()+" "+localDate.getUTCHours();

**Comment by RecordingTheSmile** [comment]
> That is understandable.
> Usually the host uses UTC (with the exception of running timexe in browser?)
> I would think, that conversion from local time to UTC, would happen in the client part of your app, or at least an understanding of the client timezone, and thereby, local timezone to convert from?
> 
> ex:
> 
> ```
> utcDate = new Date(localDate.getUTCFullYear(), localDate.getUTCMonth(), localDate.getUTCDate(), localDate.getUTCHours(), localDate.getUTCMinutes(), localDate.getUTCSeconds());
> ```

The situation of my app is, user input hour and minute in client, then server will schedule a job to run at the local timezone of the client every day. Maybe I can solve this problem by converting all the time to UTC when scheduling the job?
BTW, does timezone setting in linux have effect on schedule ?

**Comment by paragi** [comment]
Yes
Linux always use UTC internally. I think Windows does that too now.
It might depend on whether the client or server runs the timer? But it seems to be good practices to do it like you suggests.

**Comment by RecordingTheSmile** [comment]
OK, I will try it, thank you!
