### ISSUE TITLE
Single digit second/minute being skipped in list

### ISSUE THREAD

**Issue by elysianmichael** [paragi/timexe#9]
timexe('* * * * * 5 0', function)

This works. 

timexe('* * * * * 0,5,10,15,20,25,30,35,40,45,50,55 0', function)

This will not trigger on the 5th second of the minute (or the 5th minute of the hour if we move it), but the rest will trigger.

timexe('* * * * * 0,1,2,3,4,5,6,7,8,9,10 0', function)

This will skip 1-9 seconds. 0 and 10 will trigger.

**Comment by elysianmichael** [comment]
Looks like it just needs a sort function instead of the default on line 691

`        if(field[fpc].val.length>1) field[fpc].val.sort((a,b)=>a-b);
`

**Comment by paragi** [comment]
Thank you for your effort at improving this code. 
It is much appreciated.
